server:
  port: 8079

spring:
  application:
    name: RibbionClient
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl :
      defaultZone : http://localhost:8762/eureka/,http://localhost:8761/eureka/